apiVersion: v1
kind: Namespace
metadata:
  name: nexus-one
  labels:
    app.kubernetes.io/part-of: nexus-one
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted