apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-budget
  namespace: th7-enterprise-suite
spec:
  hard:
    pods: "80"
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    persistentvolumeclaims: "20"